secrets:
  # Password for user 'admin' in the cluster
  CLUSTER_ADMIN_PASSWORD: xxxx

  # Password for SCF to authenticate with UAA
  UAA_ADMIN_CLIENT_SECRET: xxxx

env:
  # Use the public IP address
  DOMAIN: mydomain.net 
            
  # uaa prefix is required
  UAA_HOST: uaa.mydomain.net
  UAA_PORT: 2793
    
  #Azure deployment requires overlay
  GARDEN_ROOTFS_DRIVER: "overlay-xfs"
    
kube:
  # List the private IP addresses
  storage_class:
    # Azure supports only "default" or "managed-premium"
    persistent: "default"
    shared: "default"
    
  registry:
    hostname: "registry.suse.com"
    username: ""
    password: ""
  organization: "cap"
  psp:
    nonprivileged: "suse.cap.psp"
    privileged: "suse.cap.psp"
services:
  loadbalanced: true
